# Generated by Django 5.2.13 on 2026-07-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('persona', models.CharField(choices=[('TRADER', 'Trader'), ('CREATEUR', 'Créateur'), ('JOURNALISTE', 'Journaliste'), ('POLITICIEN', 'Politicien'), ('PASSIONNE', 'Passionné')], max_length=20)),
                ('sources', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
