# Generated by Django 5.2.13 on 2026-04-17 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('score', models.FloatField(default=0.0)),
                ('published_at', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sources.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
