# Generated by Django 5.2.13 on 2026-06-21 15:07

from django.db import migrations, models


def clear_published_at(apps, schema_editor):
    """Vide les valeurs TEXT existantes — incompatibles avec DateTimeField."""
    Article = apps.get_model('articles', 'Article')
    Article.objects.all().update(published_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_published_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
