# Generated by Django 5.2.13 on 2026-07-25 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_otpcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('TRADER', 'Trader'), ('CREATEUR', 'Créateur'), ('JOURNALISTE', 'Journaliste'), ('POLITICIEN', 'Politicien'), ('PASSIONNE', 'Passionné')], max_length=20)),
                ('style_prompt', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('tone', models.CharField(choices=[('EXPERT', 'Expert'), ('ACCESSIBLE', 'Accessible'), ('DIRECT', 'Direct')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
