# Generated by Django 5.2.13 on 2026-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='style_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
