# Generated by Django 5.2.13 on 2026-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_profile_sector_alter_profile_style_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_digest',
            field=models.BooleanField(default=True),
        ),
    ]
