# Generated by Django 5.2.13 on 2026-07-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_post_urn_post_published_at_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
